const cursos = {
  tecnicos: [
    {
      id: 'tecWeb',
      imgSrc: '/images/web.jpg',
      title: 'Diseño y Desarrollo Web',
      descripcion: 'lorem ipsum',
      url: '/tecnicos/diseno-desarrollo-web',
    },
    {
      id: 'tecMarketing',
      imgSrc: '/images/marketing.jpg',
      title: 'Mercadeo Digital y Diseño',
      descripcion: 'lorem ipsum',
      url: '/tecnicos/mercadeo-digital-diseno',
    },
    {
      id: 'tecPostProduccion',
      imgSrc: '/images/marketing.jpg',
      title: 'PostProdución Audiovisual',
      descripcion: 'lorem ipsum',
      url: '/tecnicos/post-produccion-audiovisual',
    },
    {
      id: 'tecAnimacion3d',
      imgSrc: '/images/animacion-3d.jpg',
      title: 'Animación 3D',
      descripcion: 'lorem ipsum',
      url: '/tecnicos/animacion-3d',
    },
    {
      id: 'tecCiberseguridad',
      imgSrc: '/images/animacion-3d.jpg',
      title: 'Ciberseguridad',
      descripcion: 'lorem ipsum',
      url: '/tecnicos/ciberseguridad',
    },
    {
      id: 'tecAnalisisDatos',
      imgSrc: '/images/animacion-3d.jpg',
      title: 'Analisis y Visualización de Datos',
      descripcion: 'lorem ipsum',
      url: '/tecnicos/analisis-visualizacion-de-datos',
    },
    {
      id: 'tecPaidMedia',
      imgSrc: '/images/animacion-3d.jpg',
      title: 'Paid Media',
      descripcion: 'lorem ipsum',
      url: '/tecnicos/paid-media',
    },
    {
      id: 'tecMotionGraphics',
      imgSrc: '/images/animacion-3d.jpg',
      title: 'Motion Graphics',
      descripcion: 'lorem ipsum',
      url: '/tecnicos//images/web.jpg',
    },
  ],
  cursosLibres: [
    {
      diseno: [
        {
          id: 'clDisenoPhotoShop',
          imgSrc: 'src',
          title: 'PhotoShop',
          details: [],
          url: null,
        },
        {
          id: 'clDisenoIllustrador',
          imgSrc: 'src',
          title: 'Illustrador',
          details: [],
          url: null,
        },
        {
          id: 'clDisenoPremier',
          imgSrc: 'src',
          title: 'Premier',
          details: [],
          url: null,
        },
        {
          id: 'clDisenoAfterEffects',
          imgSrc: 'src',
          title: 'After Effects',
          details: [],
          url: null,
        },
        {
          id: 'clDisenoManejoDeRedes',
          imgSrc: 'src',
          title: 'Manejo de Redes',
          details: [],
          url: null,
        },
        {
          id: 'clDisenoDibujo',
          imgSrc: 'src',
          title: 'Dibujo',
          details: [],
          url: null,
        },
      ],
    },
    {
      computo: [
        {
          id: 'comPreparacinDigital',
          imgSrc: 'src',
          title: 'Alfabetización Digital',
          details: [],
          url: null,
        },
        {
          id: 'conWord',
          imgSrc: 'src',
          title: 'Word',
          details: [],
          url: null,
        },
        {
          id: 'comExcel',
          imgSrc: 'src',
          title: 'Excel',
          details: [],
          url: null,
        },
        {
          id: 'comPowerBi',
          imgSrc: 'src',
          title: 'Power Bi',
          details: [],
          url: null,
        },
        {
          id: 'comMultimedia',
          imgSrc: 'src',
          title: 'Multimedia',
          details: [],
          url: null,
        },
        {
          id: 'comIntroCibersecurity',
          imgSrc: 'src',
          title: 'Intro a la Ciberseguridad',
          details: [],
          url: null,
        },
      ],
    },
  ],
};

export default cursos;
