import { Providers } from './providers';
import TabsList from './components/tabs';
import Buttons from './components/buttons';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <Providers>
          <TabsList />
          <Buttons />
          {children}
        </Providers>
      </body>
    </html>
  );
}
