import { Providers } from './providers';
import Link from 'next/link';

export const metadata = {
  title: 'CETAV',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <Providers>
          <div>
            <Link href="/tecnicos">TECNICOS</Link>
          </div>
          <div>
            <Link href="/cursos-libres">CURSOS LIBRES</Link>
          </div>
          <div>
            <Link href="/about-cetav">CETAV</Link>
          </div>
          <div>
            <Link href="/egresados">EGRESADOS</Link>
          </div>
          <div>
            <Link href="/contacto">CONTACTO</Link>
          </div>
          {children}
        </Providers>
      </body>
    </html>
  );
}
